export const ExpensesActionType = {
  // type of budget
  SET_BUDGET: "Expenses@SET_BUDGET",

  // type of Expenses of different Categories
  SET_GROCERIES_EXPENSE: "Expenses@SET_GROCERIES_EXPENSE",
  SET_FOOD_EXPENSE: "Expenses@SET_FOOD_EXPENSE",
  SET_FUEL_EXPENSE: "Expenses@SET_FUEL_EXPENSE",
  SET_TRANSPORTATION_EXPENSE: "Expenses@SET_TRANSPORTATION_EXPENSE",
  SET_ENTERTAINMENT_EXPENSE: "Expenses@SET_ENTERTAINMENT_EXPENSE",
  SET_HOUSING_EXPENSE: "Expenses@SET_HOUSING_EXPENSE",
  SET_CLOTHING_EXPENSE: "Expenses@SET_CLOTHING_EXPENSE",
  SET_HEALTH_EXPENSE: "Expenses@SET_HEALTH_EXPENSE",
  SET_OTHERS_EXPENSE: "Expenses@SET_OTHERS_EXPENSE",

  // type of the array of categories
  SET_EXPENSES_DATA: "Expenses@SET_EXPENSES_DATA",

  FETCH_EXPENSES: "Expenses@FETCH_EXPENSES",

  SET_ERROR: "Expenses@SET_ERROR",
  CLEAR: "Expenses@CLEAR",
};
